[pytest]
#禁止测试标识的转义操作，并放弃向社区寻求支持的所有权利，便于参数化的ids打印中文
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True

markers =
    smoke: 冒烟测试（核心功能），部署后快速验证
    slow: 慢速测试（涉及外部 API）
    destructive: 会修改数据的测试（破坏性测试）

