[env:esp32-s3-dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
lib_deps =
    PubSubClient@^2.8

; 如果下载慢，取消下面这行的注释启用国内镜像
; platform_packages =
;     platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32/releases/download/3.1.1/esp32-arduino-lib-builder-3.1.1.zip
