"""add_is_active_to_user

Revision ID: 07f87476564d
Revises: fee1a026f2f4
Create Date: 2026-07-20 23:24:29.740327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f87476564d'
down_revision: Union[str, Sequence[str], None] = 'fee1a026f2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='账号状态：True=正常，False=已停用'))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='停用时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
