"""device_name_unique_location_index

Revision ID: c91c0fac2f85
Revises: 07f87476564d
Create Date: 2026-07-21 16:34:57.466250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c91c0fac2f85'
down_revision: Union[str, Sequence[str], None] = '07f87476564d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_name'), table_name='device')
    op.drop_index(op.f('uq_device_name_location'), table_name='device')
    op.create_index(op.f('ix_device_location'), 'device', ['location'], unique=False)
    op.create_unique_constraint(None, 'device', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='账号状态：True=正常，False=已停用',
               existing_server_default=sa.text("'1'"))
    op.drop_constraint(None, 'device', type_='unique')
    op.drop_index(op.f('ix_device_location'), table_name='device')
    op.create_index(op.f('uq_device_name_location'), 'device', ['name', 'location'], unique=True)
    op.create_index(op.f('ix_device_name'), 'device', ['name'], unique=False)
    # ### end Alembic commands ###
