"""add_device_name_location_unique_constraint

Revision ID: fee1a026f2f4
Revises: a38b71dfbc40
Create Date: 2026-07-18 22:53:28.214055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee1a026f2f4'
down_revision: Union[str, Sequence[str], None] = 'a38b71dfbc40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_device_name_location', 'device', ['name', 'location'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_device_name_location', 'device', type_='unique')
    # ### end Alembic commands ###
